FROM golang:1.21.5-alpine3.18@sha256:d8b99943fb0587b79658af03d4d4e8b57769b21dcf08a8401352a9f2a7228754 as builder

# Can be removed once testing done from go rather than bash
# gcc and libc-dev needed for go vet
RUN apk add --no-cache bash diffutils gcc libc-dev git jq openssl

WORKDIR /src/github.com/RichardoC/kube-audit-rest

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

RUN go vet ./...

# Do simple local testing
RUN ./testing/locally/local-testing.sh

# CGO_ENABLED forces a static binary
RUN CGO_ENABLED=0 GOOS=linux GOEXPERIMENT=loopvar go build -o kube-audit-rest ./cmd/kube-audit-rest/main.go

RUN mkdir /new-tmp

FROM scratch

LABEL org.opencontainers.image.source="https://github.com/RichardoC/kube-audit-rest"
LABEL org.opencontainers.image.description="Kubernetes audit logging, when you don't control the control plane"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.documentation="https://github.com/RichardoC/kube-audit-rest"
LABEL org.opencontainers.image.title="kube-audit-rest"

# Application port
EXPOSE 9090
# Metrics port
EXPOSE 55555

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /src/github.com/RichardoC/kube-audit-rest/kube-audit-rest /kube-audit-rest

# Required as distroless doesn't contain a tmp dir
COPY --from=builder /new-tmp /tmp

USER 255999


CMD ["/kube-audit-rest"]
