FROM golang:1.21.4-alpine3.18@sha256:b5ad1484ca82ce3d283af277f2f7d361bb638ec603a7b9deb79b73864eba8609 as builder

# Can be removed once testing done from go rather than bash
# gcc and libc-dev needed for go vet
RUN apk add --no-cache bash diffutils gcc libc-dev git jq openssl

WORKDIR /src/github.com/RichardoC/kube-audit-rest

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

RUN go vet ./...

# Do simple local testing
RUN ./testing/locally/local-testing.sh

# CGO_ENABLED forces a static binary
RUN CGO_ENABLED=0 GOOS=linux GOEXPERIMENT=loopvar go build -o kube-audit-rest ./cmd/kube-audit-rest/main.go

RUN mkdir /new-tmp

FROM scratch

# Application port
EXPOSE 9090
# Metrics port
EXPOSE 55555

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /src/github.com/RichardoC/kube-audit-rest/kube-audit-rest /kube-audit-rest

# Required as distroless doesn't contain a tmp dir
COPY --from=builder /new-tmp /tmp

USER 255999


CMD ["/kube-audit-rest"]
