# golang:1.21.1-alpine3.18
FROM golang@sha256:0c860c7ceba62231d0f99fb92e9d7c1577f26fea794a12c75756a8f64b146e45 as builder

# Can be removed once testing done from go rather than bash
# gcc and libc-dev needed for go vet
RUN apk add --no-cache bash diffutils gcc libc-dev git jq openssl

WORKDIR /src/github.com/RichardoC/kube-audit-rest

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .


RUN go vet ./...

# Do simple local testing
RUN ./testing/locally/local-testing.sh

# CGO_ENABLED forces a static binary
RUN CGO_ENABLED=0 GOOS=linux GOEXPERIMENT=loopvar go build -o kube-audit-rest ./cmd/kube-audit-rest/main.go

# alpine:3.18.3
FROM alpine@sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33

# Application port
EXPOSE 9090
# Metrics port
EXPOSE 55555

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /src/github.com/RichardoC/kube-audit-rest/kube-audit-rest /kube-audit-rest

USER 255999

ENTRYPOINT ["/bin/sh", "-c"]

CMD ["/kube-audit-rest"]
