FROM golang:1.26.0-alpine3.23@sha256:d4c4845f5d60c6a974c6000ce58ae079328d03ab7f721a0734277e69905473e5 AS builder

# Can be removed once testing done from go rather than bash
# gcc and libc-dev needed for go vet
RUN apk add --no-cache bash diffutils gcc libc-dev git jq openssl

WORKDIR /src/github.com/RichardoC/kube-audit-rest

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .


RUN go vet ./...

# Do simple local testing
RUN ./testing/locally/local-testing.sh

# CGO_ENABLED forces a static binary
RUN CGO_ENABLED=0 GOOS=linux go build -o kube-audit-rest ./cmd/kube-audit-rest/main.go


FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

LABEL org.opencontainers.image.source="https://github.com/RichardoC/kube-audit-rest"
LABEL org.opencontainers.image.description="Kubernetes audit logging, when you don't control the control plane"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.documentation="https://github.com/RichardoC/kube-audit-rest"
LABEL org.opencontainers.image.title="kube-audit-rest"

# Application port
EXPOSE 9090
# Metrics port
EXPOSE 55555

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=builder /src/github.com/RichardoC/kube-audit-rest/kube-audit-rest /kube-audit-rest

USER 255999

ENTRYPOINT ["/bin/sh", "-c"]

CMD ["/kube-audit-rest"]
