apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-audit-rest.fullname" . }}
  labels:
    {{- include "kube-audit-rest.labels" . | nindent 4 }}
stringData:
  fluent-bit.yaml: |
    {{- toYaml .Values.fluentBit.config | nindent 4 }}
  fluent-bit.lua: |
    {{ .Values.fluentBit.configLua | nindent 4 }}
