apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-audit-rest
  name: kube-audit-rest
  namespace: kube-audit-rest
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-audit-rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-audit-rest
    spec:
      containers:
      - image: docker.io/richardoc/kube-audit-rest:$COMMIT
        imagePullPolicy: IfNotPresent
        name: kube-audit-rest
        ports:
        - containerPort: 9090
          protocol: TCP
          name: https
        volumeMounts:
        - name: certs
          mountPath: "/etc/tls"
          readOnly: true
        - name: tmplogs
          mountPath: /tmp/
      - image: docker.elastic.co/beats/filebeat:8.2.0
        name: filebeat
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: tmplogs
          mountPath: /tmp/
          readOnly: true
        env:    
        - name: ELASTIC_CLOUD_ID
          value: "ELASTIC_CLOUD_ID_ENV"
        - name: ELASTIC_CLOUD_AUTH
          value: "ELASTIC_CLOUD_AUTH_ENV"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          secretName: kube-audit-rest
      - name: tmplogs
        hostPath:
          path: /tmp
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
