apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-audit-rest
  name: kube-audit-rest
  namespace: kube-audit-rest
spec:
  automountServiceAccountToken: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kube-audit-rest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-audit-rest
    spec:
      containers:
      - image: "docker.io/richardoc/kube-audit-rest:${COMMIT}"
        imagePullPolicy: IfNotPresent
        name: kube-audit-rest
        ports:
        - containerPort: 9090
          protocol: TCP
          name: https
        volumeMounts:
        - name: certs
          mountPath: "/etc/tls"
          readOnly: true
        - name: tmp
          mountPath: "/tmp"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 255999 # Already true in the container, but does no harm to be explicit
          runAsGroup: 255999
          fsGroup: 255999
          readOnlyRootFilesystem: true
          capabilities:
            drop: 
            - ALL 
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          secretName: kube-audit-rest
      - name: tmp
        emptyDir:
          sizeLimit: 2Gi # Based on default of 3 files at 500Mi
