apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-audit-rest
  name: kube-audit-rest
  namespace: kube-audit-rest
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 55555
    protocol: TCP
    targetPort: metrics
  selector:
    app: kube-audit-rest
  sessionAffinity: None
  type: ClusterIP

